# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20160721_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Divison',
            new_name='Division',
        ),
        migrations.RenameModel(
            old_name='Subdivison',
            new_name='Subdivision',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='subdivison',
            new_name='subdivision',
        ),
        migrations.RenameField(
            model_name='subdivision',
            old_name='divison',
            new_name='division',
        ),
    ]
