# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20160721_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='completed',
            new_name='check',
        ),
        migrations.AddField(
            model_name='cities',
            name='recordfound',
            field=models.BooleanField(default=False),
        ),
    ]
